export const DashboardHomeStyles = {
  statsGrid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8",
  chartsGrid: "grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8",
  chartCard: "bg-white p-6 rounded-xl border border-gray-100 shadow-sm h-80 flex flex-col",
  chartHeader: "flex justify-between items-center mb-4",
  chartTitle: "font-bold text-gray-800 w-[90%]",

  chartPlaceholder: "w-full h-full flex items-center justify-center text-gray-400 bg-gray-50 rounded-lg",
  columnsGrid: "grid grid-cols-1 lg:grid-cols-3 gap-6",
  cardContainer: "bg-white p-6 rounded-xl border border-gray-100 shadow-sm",
  cardTitle: "font-bold text-gray-800 mb-4",
  listContainer: "flex flex-col gap-4",
  listItem: "flex items-center gap-3 p-3 hover:bg-gray-50 rounded-lg transition-colors",
  avatar: "w-10 h-10 rounded-full",
  itemName: "font-semibold text-sm text-gray-900",
  itemDetail: "text-xs text-gray-500",
  reviewItem: "p-3 rounded-lg bg-yellow-50",
  reviewStars: "flex text-yellow-500 mb-1",
  reviewRating: "ml-2 text-xs font-bold text-yellow-700",
  reviewText: "text-sm text-gray-600 mb-2",
  reviewAuthor: "text-xs text-gray-400",
  reviewItemGray: "p-3 rounded-lg bg-gray-50",
  reviewRatingGray: "ml-2 text-xs font-bold text-gray-700",
  starGray: "text-gray-300",
};
