export const DashboardHomeStyles = {
  statsGrid: "grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 md:gap-6 mb-6 md:mb-8",
  chartsGrid: "grid grid-cols-1 xl:grid-cols-2 gap-4 md:gap-6 mb-6 md:mb-8",
  chartCard: "bg-neutral p-4 md:p-6 rounded-xl border border-border-light shadow-sm hover:shadow-md transition-shadow duration-300 h-[350px] md:h-[400px] flex flex-col overflow-hidden",
  chartHeader: "flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 md:gap-4 mb-4",
  chartTitle: "font-bold text-text-color",

  chartPlaceholder: "w-full h-full flex items-center justify-center text-text-muted bg-surface rounded-lg",
  columnsGrid: "grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 md:gap-6",
  cardContainer: "bg-neutral p-4 md:p-6 rounded-xl border border-border-light shadow-sm hover:shadow-md transition-shadow duration-300 overflow-hidden flex flex-col",
  cardTitle: "font-bold text-text-color mb-4",
  listContainer: "flex flex-col gap-4",
  listItem: "flex items-center gap-3 p-3 hover:bg-surface rounded-lg transition-colors",
  avatar: "w-10 h-10 rounded-full",
  itemName: "font-semibold text-sm text-text-color",
  itemDetail: "text-xs text-text-muted",
  reviewItem: "p-4 rounded-xl bg-gradient-to-br from-yellow-50 to-orange-50/30 border border-warning-light/50 hover:shadow-sm hover:-translate-y-0.5 transition-all duration-300",
  reviewStars: "flex text-warning mb-2",
  reviewRating: "ml-2 text-xs font-bold text-warning bg-warning-light px-2 py-0.5 rounded-full inline-flex items-center",
  reviewText: "text-sm text-text-color/90 mb-3 italic",
  reviewAuthor: "text-xs font-semibold text-text-muted",
  reviewItemGray: "p-4 rounded-xl bg-gradient-to-br from-gray-50 to-slate-50 border border-border-light/50 hover:shadow-sm hover:-translate-y-0.5 transition-all duration-300",
  reviewRatingGray: "ml-2 text-xs font-bold text-text-color/90 bg-border-light px-2 py-0.5 rounded-full inline-flex items-center",
  starGray: "text-gray-300",
};
