export const ReservationSummaryStyle = {
    cardContainer: "relative w-full h-fit px-4 py-6 bg-neutral flex flex-col md:w-full md:max-w-sm md:mt-6 shadow-lg rounded-xl",
    priceHeader: "flex items-center justify-between",
    priceWithOffer: "text-2xl font-bold text-text-color",
    priceDefault: "text-2xl font-bold",
    perNightText: "text-lg font-normal opacity-70",
    offerBadge: "bg-green-200 text-primary text-xs font-bold px-3 flex items-center justify-center gap-1 py-2 rounded-full",
    datePickerWrapper: "flex justify-between w-full mt-4 gap-2",
    dateInputBox: "flex flex-col border border-border-light/80 w-1/2 justify-center px-4 py-2 gap-1 text-lg rounded-md items-center cursor-pointer",
    dateInputLabel: "text-sm opacity-70 w-full",
    calendarContainer: "absolute top-25 mt-2 z-20",
    divider: "w-full h-[1px] bg-border-light my-6",
    summaryContainer: "flex flex-col gap-1",
    summaryRow: "flex justify-between w-full",
    summaryRowDiscount: "flex justify-between w-full text-success",
    summaryLabel: "font-medium opacity-70",
    summaryValue: "font-medium",
    dividerShort: "w-full h-[1px] bg-border-light my-4",
    buttonWrapper: "w-full mt-6",
    disclaimer: "w-full mt-3 text-center opacity-60",
    featuresContainer: "flex flex-col gap-2 mt-6",
    featureItem: "flex items-center gap-4",
    featureIcon: "text-success",
  };