export const RoomDescriptionStyle = {
    mainSection: "w-full max-w-screen-2xl mx-auto my-2 flex flex-col px-4 sm:px-6 lg:px-8 text-text-color text-start font-body relative",
    carouselWrapper: "flex h-[300px] md:h-[500px]",
    contentWrapper: "flex flex-col md:flex-row gap-4 justify-between w-full",
    detailsColumn: "flex flex-col gap-4 w-full mb-10",
    titleSection: "mt-6 flex flex-col gap-2",
    mainHeading: "font-heading text-3xl md:text-4xl font-semi-bold",
    ratingWrapper: "flex gap-2 items-center",
    ratingValue: "font-semibold",
    ratingCount: "opacity-70",
    infoCardsWrapper: "flex gap-2 justify-between md:max-w-2/5",
    infoCard: "flex flex-col gap-1 items-center justify-center bg-neutral min-w-[120px] py-3 rounded-md text-icons-secondary shadow-sm",
    infoCardText: "font-medium text-text-color",
    subsection: "flex flex-col gap-4 md:max-w-4/5",
    subheading: "font-heading text-lg md:text-2xl font-semi-bold",
    descriptionText: "whitespace-pre-wrap opacity-80",
    amenitiesList: "list-none flex flex-col gap-2 md:grid md:grid-cols-2",
    amenityItem: "flex items-center gap-2 text-icons-secondary",
    amenityIcon: "mr-2",
    amenityText: "font-medium text-text-color",
    rulesWrapper: "flex flex-col gap-4 md:flex-row md:justify-between md:align-items w-full",
    rulesColumn: "flex flex-col gap-1 md:w-1/2",
    rulesTitle: "text-md font-medium",
    rulesText: "opacity-80",
    rulesHighlight: "font-medium",
  };