export const Contactstyles = {
  container: "bg-background max-w-screen-2xl mx-auto flex flex-col justify-between px-4 sm:px-6 lg:px-8 w-full",
  content: "w-full my-20",
  header: "text-center mb-12 md:mb-16 text-text-color",
  title: "text-4xl md:text-5xl font-bold tracking-tight font-heading",
  subtitle: "mt-4 text-lg max-w-2xl mx-auto opacity-60 font-body",
  main: "grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16",
  infoContainer: "flex flex-col space-y-12",
  infoCard: "bg-neutral p-8 rounded-lg shadow-lg",
  infoCardTitle: "text-2xl font-semibold text-text-color font-heading mb-6",
  infoList: "space-y-6 text-text-color font-body",
  infoListItem: "flex items-center",
  infoListItemContent: "ml-4",
  infoListItemTitle: "font-semibold",
  infoListItemText: "font-body opacity-70",
  mapContainer: "h-80 md:h-96 w-full rounded-lg overflow-hidden shadow-lg",
  formContainer: "bg-neutral p-8 rounded-lg shadow-lg",
  form: "space-y-6",
  formLabel: "block text-sm font-medium text-text-color mb-2",
  formInput: "w-full bg-background-input border border-gray-300 rounded-md py-2 px-3 text-text-color placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary transition",
  formTextarea: "w-full bg-background-input border border-gray-300 rounded-md py-2 px-3 text-text-color placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary transition",
  buttonContainer: "mt-8",
  submitMessage: "mt-4 text-center text-primary",
};
