export const ReviewsStyles = {
  container: "space-y-6",
  header: "flex justify-between items-center",
  title: "text-2xl font-bold text-text-color",
  listContainer: "space-y-4",
  card: "bg-neutral p-6 rounded-xl border border-border-light shadow-sm",
  cardHeader: "flex justify-between items-start mb-4",
  userInfo: "flex items-center gap-3",
  avatar: "w-10 h-10 rounded-full",
  userName: "font-semibold text-text-color",
  date: "text-xs text-text-muted",
  starsContainer: "flex text-warning",
  starActive: "text-yellow-400",
  starInactive: "text-gray-300",
  comment: "text-text-color/80 leading-relaxed",
};
