export { default as HeroBanner } from "./HeroBanner";
export { default as CheckBox } from "./CheckBox";
export { default as Button} from "./Button";
export { default as AboutUs } from "./AboutUs";
export { default as WhyRegency } from "./WhyRegency";
export { default as HomeRooms } from "./HomeRooms"
export { default as RoomsCard } from "./RoomsCard";
export { default as Carousel } from "./CarouselHome";
export { default as Amenities } from "./Amenities";
export { default as GuestExperience } from "./GuestExperience";
export { default as FormLogin } from "./FormLogin";
export { default as FormRegistration } from "./FormRegistration"
export { default as CarouselRegister } from "./CarouselRegister";
export { default as FormLoginVerifyEmail } from "./FormLoginVerifyEmail"
export { default as FormForgotPassword } from "./FormForgotPassword"
export { default as FormResetPassword } from "./FormResetPassword"
export { default as FilterRooms } from "./FilterRooms"
export { default as RoomsSection } from "./RoomsSection"
export { default as RoomDescription } from "./RoomDescription"
export { default as RoomRecommendation } from "./RoomRecommendation"
export { default as ReservationSummary } from "./ReservationSummary/ReservationSummary"